<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlogCategory extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('blog_category');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('icon', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $this->hasMany('BlogPost', array('local' => 'id',
                                     'foreign' => 'category_id'));

    $timestampable0 = new Doctrine_Template_Timestampable();
    $sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'name'), 'name' => 'slug', 'type' => 'string', 'length' => '255'));
    $this->actAs($timestampable0);
    $this->actAs($sluggable0);
  }
}