<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlogPostTag extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('blog_post_tag');
    $this->hasColumn('blog_post_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('blog_tag_id', 'integer', null, array('type' => 'integer', 'primary' => true));
  }

}