<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlogComment extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('blog_comment');
    $this->hasColumn('post_id', 'integer', 20, array('type' => 'integer', 'length' => '20'));
    $this->hasColumn('author', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('email', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('site', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('content', 'string', 6000, array('type' => 'string', 'length' => '6000'));
    $this->hasColumn('ipv4', 'string', 16, array('type' => 'string', 'length' => '16'));
    $this->hasColumn('ipv6', 'string', 64, array('type' => 'string', 'length' => '64'));
    $this->hasColumn('spam', 'boolean', null, array('type' => 'boolean', 'default' => false));
  }

  public function setUp()
  {
    $this->hasOne('BlogPost as Post', array('local' => 'post_id',
                                            'foreign' => 'id',
                                            'onDelete' => 'CASCADE'));

    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}